// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF-zXIs5q0Fk8wV2q_1ghTXoaTbXCYUKA',
    appId: '1:548183651248:web:ea174bb8f894a06cfc1c75',
    messagingSenderId: '548183651248',
    projectId: 'soundwordbuilder',
    authDomain: 'soundwordbuilder.firebaseapp.com',
    storageBucket: 'soundwordbuilder.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcXTTio5dd_Y61XvlCDRCUs8gkfbU1x-s',
    appId: '1:548183651248:android:6317a8f72fad2b9dfc1c75',
    messagingSenderId: '548183651248',
    projectId: 'soundwordbuilder',
    storageBucket: 'soundwordbuilder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPdfDyMsqNe_iU6Rej9mjRX7I08X9niyU',
    appId: '1:548183651248:ios:6161bba87b1a5025fc1c75',
    messagingSenderId: '548183651248',
    projectId: 'soundwordbuilder',
    storageBucket: 'soundwordbuilder.firebasestorage.app',
    iosClientId: '548183651248-pg20cibrgnvv4jefl5q658n66ojt7lsq.apps.googleusercontent.com',
    iosBundleId: 'com.soundwordbuilder.soundwordbuilderFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPdfDyMsqNe_iU6Rej9mjRX7I08X9niyU',
    appId: '1:548183651248:ios:6161bba87b1a5025fc1c75',
    messagingSenderId: '548183651248',
    projectId: 'soundwordbuilder',
    storageBucket: 'soundwordbuilder.firebasestorage.app',
    iosClientId: '548183651248-pg20cibrgnvv4jefl5q658n66ojt7lsq.apps.googleusercontent.com',
    iosBundleId: 'com.soundwordbuilder.soundwordbuilderFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF-zXIs5q0Fk8wV2q_1ghTXoaTbXCYUKA',
    appId: '1:548183651248:web:6231b60ffba4dd15fc1c75',
    messagingSenderId: '548183651248',
    projectId: 'soundwordbuilder',
    authDomain: 'soundwordbuilder.firebaseapp.com',
    storageBucket: 'soundwordbuilder.firebasestorage.app',
  );
}